### ISSUE TITLE
Make dangling links case-insensitive in 'Group by dangling link'

### ISSUE THREAD

**Issue by Taitava** [graydon/obsidian-dangling-links#12]
Consider the following text:

```
[[Cats]] like to play a lot. On the other hand, [[cats]] also tend to sleep a lot.
````

This causes the list of dangling links to have two almost similar links: `Cats` and `cats`. They could be combined into one in the list.

Dangling links version: 0.3.0

**Comment by claremacrae** [comment]
Thanks for the report.

tl;dr This was fixed at some point.

---

I just tested it with this setup:

```
SYSTEM INFO:
	Obsidian version: v1.5.4
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 23.2.0
```

With this markdown:

```
[[Cats]]

[[cats]]
```

A promising sign was that the links were grouped together:

![image](https://github.com/graydon/obsidian-dangling-links/assets/4840096/b8b1a0c9-cc21-4db5-8794-cd6a27ab959c)

When I created one of the files, both disappeared from the Dangling links panel:

![image](https://github.com/graydon/obsidian-dangling-links/assets/4840096/8acd4a38-f949-411c-9036-f3d57d7011c5)

**Comment by Taitava** [comment]
I guess it depends on the "group by" mode. If using _Group by dangling link_, they still show seprately. I didn't notice to mention this in my original post.
![kuva](https://github.com/graydon/obsidian-dangling-links/assets/13002142/7215dedd-2617-49d5-b05d-7c1ca515db97)
- Dangling links 0.30.0
- Obsidian 1.5.4

**Comment by claremacrae** [comment]
> I guess it depends on the "group by" mode. If using _Group by dangling link_, they still show seprately. I didn't notice to mention this in my original post. 

Ah great, that extra info is helpful. Thank you.

I've renamed the issue, and am re-opening.
